version: '2'
services:
  webhost:
    image: plank-games:latest
    ports:
      - 4000:4000
    environment:
      SECRET_KEY_BASE: ${PLANK_GAMES_SECRET_KEY_BASE}
      RELEASE_COOKIE: ${RELEASE_COOKIE}