apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: plank-games
namespace: default
resources:
  - service.yaml
  - ingress.yaml
  - redis.yaml
  - secret.yaml
  - deployment.yaml
