apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: prod
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: plank-games-ingress
    path: ingress-patches.yaml
patchesStrategicMerge:
  - secret.yaml
